// Mocks generated by Mockito 5.4.6 from annotations
// in supporttickets_app/test/features/work_sessions/viewmodels/work_session_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:supporttickets_app/features/work_sessions/models/work_session.dart'
    as _i2;
import 'package:supporttickets_app/features/work_sessions/repositories/work_session_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorkSession_0 extends _i1.SmartFake implements _i2.WorkSession {
  _FakeWorkSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WorkSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkSessionRepository extends _i1.Mock
    implements _i3.WorkSessionRepository {
  MockWorkSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<Map<String, dynamic>> getWorkSessions({int? page = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#getWorkSessions, [], {#page: page}),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.WorkSession?> getCurrentSession() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentSession, []),
            returnValue: _i4.Future<_i2.WorkSession?>.value(),
          )
          as _i4.Future<_i2.WorkSession?>);

  @override
  _i4.Future<_i2.WorkSession> startSession() =>
      (super.noSuchMethod(
            Invocation.method(#startSession, []),
            returnValue: _i4.Future<_i2.WorkSession>.value(
              _FakeWorkSession_0(this, Invocation.method(#startSession, [])),
            ),
          )
          as _i4.Future<_i2.WorkSession>);

  @override
  _i4.Future<_i2.WorkSession> pauseSession() =>
      (super.noSuchMethod(
            Invocation.method(#pauseSession, []),
            returnValue: _i4.Future<_i2.WorkSession>.value(
              _FakeWorkSession_0(this, Invocation.method(#pauseSession, [])),
            ),
          )
          as _i4.Future<_i2.WorkSession>);

  @override
  _i4.Future<_i2.WorkSession> resumeSession() =>
      (super.noSuchMethod(
            Invocation.method(#resumeSession, []),
            returnValue: _i4.Future<_i2.WorkSession>.value(
              _FakeWorkSession_0(this, Invocation.method(#resumeSession, [])),
            ),
          )
          as _i4.Future<_i2.WorkSession>);

  @override
  _i4.Future<_i2.WorkSession> endSession() =>
      (super.noSuchMethod(
            Invocation.method(#endSession, []),
            returnValue: _i4.Future<_i2.WorkSession>.value(
              _FakeWorkSession_0(this, Invocation.method(#endSession, [])),
            ),
          )
          as _i4.Future<_i2.WorkSession>);

  @override
  _i4.Future<void> deleteSession(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [sessionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getReports({
    int? page = 1,
    String? userId,
    String? date,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getReports, [], {
              #page: page,
              #userId: userId,
              #date: date,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);
}
