// Mocks generated by Mockito 5.4.6 from annotations
// in supporttickets_app/test/features/users/viewmodels/user_management_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:supporttickets_app/core/network/api_client.dart' as _i2;
import 'package:supporttickets_app/features/users/models/user_model.dart'
    as _i3;
import 'package:supporttickets_app/features/users/repositories/user_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i4.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i5.Future<List<_i3.UserModel>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i5.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i5.Future<List<_i3.UserModel>>);

  @override
  _i5.Future<List<_i3.UserModel>> getCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomers, []),
            returnValue: _i5.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i5.Future<List<_i3.UserModel>>);

  @override
  _i5.Future<List<_i3.UserModel>> getSupporters() =>
      (super.noSuchMethod(
            Invocation.method(#getSupporters, []),
            returnValue: _i5.Future<List<_i3.UserModel>>.value(
              <_i3.UserModel>[],
            ),
          )
          as _i5.Future<List<_i3.UserModel>>);

  @override
  _i5.Future<_i3.UserModel> createUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [userData]),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#createUser, [userData]),
              ),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<_i3.UserModel> updateUser(
    int? userId,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [userId, userData]),
            returnValue: _i5.Future<_i3.UserModel>.value(
              _FakeUserModel_1(
                this,
                Invocation.method(#updateUser, [userId, userData]),
              ),
            ),
          )
          as _i5.Future<_i3.UserModel>);

  @override
  _i5.Future<void> deleteUser(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
