// Mocks generated by Mockito 5.4.6 from annotations
// in supporttickets_app/test/features/tickets/viewmodels/ticket_details_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:file_picker/file_picker.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:supporttickets_app/core/network/api_client.dart' as _i2;
import 'package:supporttickets_app/features/profile/repositories/profile_repository.dart'
    as _i8;
import 'package:supporttickets_app/features/tickets/models/ticket.dart' as _i3;
import 'package:supporttickets_app/features/tickets/models/ticket_message.dart'
    as _i4;
import 'package:supporttickets_app/features/tickets/repositories/ticket_repository.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTicket_1 extends _i1.SmartFake implements _i3.Ticket {
  _FakeTicket_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTicketMessage_2 extends _i1.SmartFake implements _i4.TicketMessage {
  _FakeTicketMessage_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TicketRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTicketRepository extends _i1.Mock implements _i5.TicketRepository {
  MockTicketRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i6.Future<void> fetchEmails() =>
      (super.noSuchMethod(
            Invocation.method(#fetchEmails, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomers, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getTags() =>
      (super.noSuchMethod(
            Invocation.method(#getTags, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<_i3.Ticket>> getTickets({Map<String, dynamic>? filters}) =>
      (super.noSuchMethod(
            Invocation.method(#getTickets, [], {#filters: filters}),
            returnValue: _i6.Future<List<_i3.Ticket>>.value(<_i3.Ticket>[]),
          )
          as _i6.Future<List<_i3.Ticket>>);

  @override
  _i6.Future<_i3.Ticket> getTicket(int? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#getTicket, [ticketId]),
            returnValue: _i6.Future<_i3.Ticket>.value(
              _FakeTicket_1(this, Invocation.method(#getTicket, [ticketId])),
            ),
          )
          as _i6.Future<_i3.Ticket>);

  @override
  _i6.Future<List<_i4.TicketMessage>> getTicketMessages(
    int? ticketId, [
    int? userId,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getTicketMessages, [ticketId, userId]),
            returnValue: _i6.Future<List<_i4.TicketMessage>>.value(
              <_i4.TicketMessage>[],
            ),
          )
          as _i6.Future<List<_i4.TicketMessage>>);

  @override
  _i6.Future<_i3.Ticket> createTicket(
    String? title,
    String? description, {
    int? customerId,
    String? senderEmail,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createTicket,
              [title, description],
              {#customerId: customerId, #senderEmail: senderEmail},
            ),
            returnValue: _i6.Future<_i3.Ticket>.value(
              _FakeTicket_1(
                this,
                Invocation.method(
                  #createTicket,
                  [title, description],
                  {#customerId: customerId, #senderEmail: senderEmail},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Ticket>);

  @override
  _i6.Future<Map<String, dynamic>> assignTicket(
    int? ticketId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignTicket, [ticketId, data]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i3.Ticket> updateTicketStatus(int? ticketId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTicketStatus, [ticketId, status]),
            returnValue: _i6.Future<_i3.Ticket>.value(
              _FakeTicket_1(
                this,
                Invocation.method(#updateTicketStatus, [ticketId, status]),
              ),
            ),
          )
          as _i6.Future<_i3.Ticket>);

  @override
  _i6.Future<_i3.Ticket> syncTags(int? ticketId, List<int>? tagIds) =>
      (super.noSuchMethod(
            Invocation.method(#syncTags, [ticketId, tagIds]),
            returnValue: _i6.Future<_i3.Ticket>.value(
              _FakeTicket_1(
                this,
                Invocation.method(#syncTags, [ticketId, tagIds]),
              ),
            ),
          )
          as _i6.Future<_i3.Ticket>);

  @override
  _i6.Future<void> deleteTicket(int? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTicket, [ticketId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.TicketMessage> sendMessage(
    int? ticketId,
    String? message, {
    int? userId,
    _i7.PlatformFile? attachment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [ticketId, message],
              {#userId: userId, #attachment: attachment},
            ),
            returnValue: _i6.Future<_i4.TicketMessage>.value(
              _FakeTicketMessage_2(
                this,
                Invocation.method(
                  #sendMessage,
                  [ticketId, message],
                  {#userId: userId, #attachment: attachment},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.TicketMessage>);

  @override
  _i6.Future<Map<String, dynamic>> tickTime(
    int? ticketId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tickTime, [ticketId, data]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i8.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i6.Future<Map<String, dynamic>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [data]),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);
}
