// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYcPWGzonpYgerhNT0k3wbSl6jh2Z87Xg',
    appId: '1:930751298095:web:328512a103bd0dfeb2a4da',
    messagingSenderId: '930751298095',
    projectId: 'support-tickets-app-31f91',
    authDomain: 'support-tickets-app-31f91.firebaseapp.com',
    storageBucket: 'support-tickets-app-31f91.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoejtUnLE83kQKuZGF9MvP7I4hnWQMJk',
    appId: '1:930751298095:android:0095b42abb9ede4db2a4da',
    messagingSenderId: '930751298095',
    projectId: 'support-tickets-app-31f91',
    storageBucket: 'support-tickets-app-31f91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUgVn6Z2ttkcSPbk2JMBjJl0rjbioG7Us',
    appId: '1:930751298095:ios:b6add81e308c4b5fb2a4da',
    messagingSenderId: '930751298095',
    projectId: 'support-tickets-app-31f91',
    storageBucket: 'support-tickets-app-31f91.firebasestorage.app',
    iosBundleId: 'com.example.supportticketsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUgVn6Z2ttkcSPbk2JMBjJl0rjbioG7Us',
    appId: '1:930751298095:ios:b6add81e308c4b5fb2a4da',
    messagingSenderId: '930751298095',
    projectId: 'support-tickets-app-31f91',
    storageBucket: 'support-tickets-app-31f91.firebasestorage.app',
    iosBundleId: 'com.example.supportticketsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYcPWGzonpYgerhNT0k3wbSl6jh2Z87Xg',
    appId: '1:930751298095:web:8108e7dba3601884b2a4da',
    messagingSenderId: '930751298095',
    projectId: 'support-tickets-app-31f91',
    authDomain: 'support-tickets-app-31f91.firebaseapp.com',
    storageBucket: 'support-tickets-app-31f91.firebasestorage.app',
  );
}
