import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Import the actual ApiClient from your lib folder using the package name defined in pubspec.yaml
import 'package:supporttickets_app/core/network/api_client.dart';

/// This file will be generated by build_runner
import 'api_client_test.mocks.dart';

/// Generates mock classes for Dio and SharedPreferences
@GenerateMocks([Dio, SharedPreferences])
void main() {
  late ApiClient apiClient;
  late MockDio mockDio;
  late MockSharedPreferences mockPrefs;

  setUp(() {
    mockDio = MockDio();
    mockPrefs = MockSharedPreferences();
    
    /// Stub the options getter since ApiClient accesses it during initialization
    when(mockDio.options).thenReturn(BaseOptions());
    when(mockDio.interceptors).thenReturn(Interceptors());

    apiClient = ApiClient(mockDio, mockPrefs);
  });

  group('ApiClient Tests', () {
    test('Should return data successfully on GET request', () async {
      /// Arrange expected mock behavior
      final expectedData = {'success': true, 'message': 'Data retrieved'};
      final response = Response(
        requestOptions: RequestOptions(path: '/test'),
        data: expectedData,
        statusCode: 200,
      );
      
      when(mockDio.get(any, queryParameters: anyNamed('queryParameters')))
          .thenAnswer((_) async => response);

      /// Act
      final result = await apiClient.get('/test');

      /// Assert results
      expect(result, equals(expectedData));
      verify(mockDio.get('/test', queryParameters: null)).called(1);
    });

    test('Should throw Exception with API message on POST error', () async {
      /// Arrange error mock behavior
      final errorResponse = Response(
        requestOptions: RequestOptions(path: '/test'),
        statusCode: 422,
        data: {'message': 'Invalid credentials'},
      );
      
      when(mockDio.post(any, data: anyNamed('data'))).thenThrow(
        DioException(
          requestOptions: RequestOptions(path: '/test'),
          response: errorResponse,
        ),
      );

      /// Act & Assert expected exception
      expect(
        () => apiClient.post('/test', data: {'email': 'test@test.com'}),
        throwsA(isA<Exception>().having((e) => e.toString(), 'message', contains('Invalid credentials'))),
      );
    });
  });
}