// Mocks generated by Mockito 5.4.6 from annotations
// in supporttickets_app/test/features/auth/ui/login_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:shared_preferences/shared_preferences.dart' as _i3;
import 'package:supporttickets_app/core/network/api_client.dart' as _i2;
import 'package:supporttickets_app/features/auth/repositories/auth_repository.dart'
    as _i6;
import 'package:supporttickets_app/features/profile/repositories/profile_repository.dart'
    as _i10;
import 'package:supporttickets_app/features/tickets/models/ticket.dart' as _i4;
import 'package:supporttickets_app/features/tickets/models/ticket_message.dart'
    as _i5;
import 'package:supporttickets_app/features/tickets/repositories/ticket_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTicket_2 extends _i1.SmartFake implements _i4.Ticket {
  _FakeTicket_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTicketMessage_3 extends _i1.SmartFake implements _i5.TicketMessage {
  _FakeTicketMessage_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i6.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i3.SharedPreferences get prefs =>
      (super.noSuchMethod(
            Invocation.getter(#prefs),
            returnValue: _FakeSharedPreferences_1(
              this,
              Invocation.getter(#prefs),
            ),
          )
          as _i3.SharedPreferences);

  @override
  _i7.Future<bool> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [TicketRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTicketRepository extends _i1.Mock implements _i8.TicketRepository {
  MockTicketRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCustomers() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomers, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<_i4.Ticket>> getTickets({Map<String, dynamic>? filters}) =>
      (super.noSuchMethod(
            Invocation.method(#getTickets, [], {#filters: filters}),
            returnValue: _i7.Future<List<_i4.Ticket>>.value(<_i4.Ticket>[]),
          )
          as _i7.Future<List<_i4.Ticket>>);

  @override
  _i7.Future<_i4.Ticket> getTicket(int? ticketId) =>
      (super.noSuchMethod(
            Invocation.method(#getTicket, [ticketId]),
            returnValue: _i7.Future<_i4.Ticket>.value(
              _FakeTicket_2(this, Invocation.method(#getTicket, [ticketId])),
            ),
          )
          as _i7.Future<_i4.Ticket>);

  @override
  _i7.Future<List<_i5.TicketMessage>> getTicketMessages(
    int? ticketId, [
    int? userId,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getTicketMessages, [ticketId, userId]),
            returnValue: _i7.Future<List<_i5.TicketMessage>>.value(
              <_i5.TicketMessage>[],
            ),
          )
          as _i7.Future<List<_i5.TicketMessage>>);

  @override
  _i7.Future<_i4.Ticket> createTicket(
    String? title,
    String? description, {
    int? customerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createTicket,
              [title, description],
              {#customerId: customerId},
            ),
            returnValue: _i7.Future<_i4.Ticket>.value(
              _FakeTicket_2(
                this,
                Invocation.method(
                  #createTicket,
                  [title, description],
                  {#customerId: customerId},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.Ticket>);

  @override
  _i7.Future<Map<String, dynamic>> assignTicket(
    int? ticketId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignTicket, [ticketId, data]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i4.Ticket> updateTicketStatus(int? ticketId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateTicketStatus, [ticketId, status]),
            returnValue: _i7.Future<_i4.Ticket>.value(
              _FakeTicket_2(
                this,
                Invocation.method(#updateTicketStatus, [ticketId, status]),
              ),
            ),
          )
          as _i7.Future<_i4.Ticket>);

  @override
  _i7.Future<_i5.TicketMessage> sendMessage(
    int? ticketId,
    String? message, {
    int? userId,
    _i9.File? attachment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [ticketId, message],
              {#userId: userId, #attachment: attachment},
            ),
            returnValue: _i7.Future<_i5.TicketMessage>.value(
              _FakeTicketMessage_3(
                this,
                Invocation.method(
                  #sendMessage,
                  [ticketId, message],
                  {#userId: userId, #attachment: attachment},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.TicketMessage>);

  @override
  _i7.Future<Map<String, dynamic>> tickTime(
    int? ticketId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#tickTime, [ticketId, data]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i10.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i7.Future<Map<String, dynamic>> getProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, []),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> updateProfile(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [data]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);
}
